---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14021.
--- DateTime: 2024-04-14 12:24
---

if(redis.call('GET',KEYS[1])==ARGV[1]) then

    return redis.call('DEL',KEYS[1])
end

return 0